### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by tobsn** [dosx/node-vips#1]
latest OSX:

`$ node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.19 
Checking for vips-7.26                   : not found 
Checking for exiv2                       : yes 
'configure' finished successfully (0.341s)
Waf: Entering directory `/Users/tobias/Documents/test/node/node_modules/node-vips/build'
[1/3] cxx: src/node-vips.cc -> build/Release/src/node-vips_1.o
[2/3] cxx: src/transform.cc -> build/Release/src/transform_1.o
In file included from ../src/transform.cc:39:
/usr/local/include/vips/vips.h:84:18: error: glib.h: No such file or directory
/usr/local/include/vips/vips.h:85:25: error: glib/gstdio.h: No such file or directory
/usr/local/include/vips/vips.h:86:21: error: gmodule.h: No such file or directory
/usr/local/include/vips/vips.h:87:25: error: glib-object.h: No such file or directory
In file included from /usr/local/include/vips/vips.h:99,
                 from ../src/transform.cc:39:
/usr/local/include/vips/buf.h:51: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:53: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:68: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:69: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:70: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:72: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:73: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:74: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:75: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:76: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:77: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:78: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:79: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:80: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:83: error: ‘gboolean’ does not name a type
/usr/local/include/vips/buf.h:84: error: ‘gboolean’ does not name a type
In file included from /usr/local/include/vips/vips.h:100,
                 from ../src/transform.cc:39:
/usr/local/include/vips/util.h:151: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/util.h:151: error: expected primary-expression before ‘int’
/usr/local/include/vips/util.h:151: error: initializer expression list treated as compound expression
/usr/local/include/vips/util.h:152: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/util.h:152: error: expected primary-expression before ‘int’
/usr/local/include/vips/util.h:152: error: initializer expression list treated as compound expression
/usr/local/include/vips/util.h:154: error: ‘gboolean’ does not name a type
/usr/local/include/vips/util.h:155: error: ‘GSList’ was not declared in this scope
/usr/local/include/vips/util.h:155: error: ‘list’ was not declared in this scope
/usr/local/include/vips/util.h:155: error: expected primary-expression before ‘fn’
/usr/local/include/vips/util.h:155: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:155: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:155: error: initializer expression list treated as compound expression
/usr/local/include/vips/util.h:156: error: ‘GSList’ was not declared in this scope
/usr/local/include/vips/util.h:156: error: ‘list’ was not declared in this scope
/usr/local/include/vips/util.h:156: error: expected primary-expression before ‘fn’
/usr/local/include/vips/util.h:156: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:156: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:156: error: initializer expression list treated as compound expression
/usr/local/include/vips/util.h:157: error: ‘GSList’ was not declared in this scope
/usr/local/include/vips/util.h:157: error: ‘list’ was not declared in this scope
/usr/local/include/vips/util.h:158: error: expected primary-expression before ‘fn’
/usr/local/include/vips/util.h:158: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:158: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:158: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:158: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:158: error: initializer expression list treated as compound expression
/usr/local/include/vips/util.h:159: error: ‘GSList’ was not declared in this scope
/usr/local/include/vips/util.h:159: error: ‘list’ was not declared in this scope
/usr/local/include/vips/util.h:159: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:160: error: expected primary-expression before ‘fn’
/usr/local/include/vips/util.h:160: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:160: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:160: error: initializer expression list treated as compound expression
/usr/local/include/vips/util.h:161: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/local/include/vips/util.h:162: error: variable or field ‘vips_slist_free_all’ declared void
/usr/local/include/vips/util.h:162: error: ‘GSList’ was not declared in this scope
/usr/local/include/vips/util.h:162: error: ‘list’ was not declared in this scope
/usr/local/include/vips/util.h:165: error: ‘GHashTable’ was not declared in this scope
/usr/local/include/vips/util.h:165: error: ‘hash’ was not declared in this scope
/usr/local/include/vips/util.h:166: error: expected primary-expression before ‘fn’
/usr/local/include/vips/util.h:166: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:166: error: expected primary-expression before ‘void’
/usr/local/include/vips/util.h:166: error: initializer expression list treated as compound expression
/usr/local/include/vips/util.h:170: error: ‘gboolean’ does not name a type
/usr/local/include/vips/util.h:171: error: ‘gboolean’ does not name a type
/usr/local/include/vips/util.h:185: error: ‘gint64’ does not name a type
/usr/local/include/vips/util.h:189: error: ‘gboolean’ has not been declared
/usr/local/include/vips/util.h:191: error: ‘gboolean’ has not been declared
/usr/local/include/vips/util.h:198: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/local/include/vips/util.h:199: error: variable or field ‘vips__gslist_gvalue_free’ declared void
/usr/local/include/vips/util.h:199: error: ‘GSList’ was not declared in this scope
/usr/local/include/vips/util.h:199: error: ‘list’ was not declared in this scope
/usr/local/include/vips/util.h:200: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/local/include/vips/util.h:201: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/local/include/vips/util.h:202: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/local/include/vips/util.h:204: error: ‘gint64’ has not been declared
/usr/local/include/vips/util.h:205: error: ‘gint64’ has not been declared
In file included from /usr/local/include/vips/vips.h:101,
                 from ../src/transform.cc:39:
/usr/local/include/vips/object.h:244: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/object.h:260: error: ‘guint’ does not name a type
/usr/local/include/vips/object.h:278: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:283: error: ‘gulong’ does not name a type
/usr/local/include/vips/object.h:289: error: ‘GHashTable’ does not name a type
/usr/local/include/vips/object.h:293: error: ‘VipsArgumentTable’ was not declared in this scope
/usr/local/include/vips/object.h:293: error: expected primary-expression before ‘,’ token
/usr/local/include/vips/object.h:294: error: ‘GParamSpec’ was not declared in this scope
/usr/local/include/vips/object.h:294: error: expected primary-expression before ‘)’ token
/usr/local/include/vips/object.h:294: error: initializer expression list treated as compound expression
/usr/local/include/vips/object.h:295: error: ‘GParamSpec’ has not been declared
/usr/local/include/vips/object.h:296: error: ‘GObject’ has not been declared
/usr/local/include/vips/object.h:296: error: ‘GObject’ has not been declared
/usr/local/include/vips/object.h:297: error: ‘GParamSpec’ has not been declared
/usr/local/include/vips/object.h:301: error: ‘GParamSpec’ has not been declared
/usr/local/include/vips/object.h:306: error: ‘GParamSpec’ has not been declared
/usr/local/include/vips/object.h:309: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:388: error: ‘GObject’ does not name a type
/usr/local/include/vips/object.h:393: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:398: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:402: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/object.h:412: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:413: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:414: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:418: error: ‘GObjectClass’ does not name a type
/usr/local/include/vips/object.h:480: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:502: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/object.h:503: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/object.h:506: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:507: error: variable or field ‘vips_object_set_property’ declared void
/usr/local/include/vips/object.h:507: error: ‘GObject’ was not declared in this scope
/usr/local/include/vips/object.h:507: error: ‘gobject’ was not declared in this scope
/usr/local/include/vips/object.h:508: error: ‘guint’ was not declared in this scope
/usr/local/include/vips/object.h:508: error: expected primary-expression before ‘const’
/usr/local/include/vips/object.h:508: error: ‘GParamSpec’ was not declared in this scope
/usr/local/include/vips/object.h:508: error: ‘pspec’ was not declared in this scope
/usr/local/include/vips/object.h:509: error: variable or field ‘vips_object_get_property’ declared void
/usr/local/include/vips/object.h:509: error: ‘GObject’ was not declared in this scope
/usr/local/include/vips/object.h:509: error: ‘gobject’ was not declared in this scope
/usr/local/include/vips/object.h:510: error: ‘guint’ was not declared in this scope
/usr/local/include/vips/object.h:510: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/object.h:510: error: ‘value’ was not declared in this scope
/usr/local/include/vips/object.h:510: error: ‘GParamSpec’ was not declared in this scope
/usr/local/include/vips/object.h:510: error: ‘pspec’ was not declared in this scope
/usr/local/include/vips/object.h:524: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:526: error: ‘GType’ does not name a type
/usr/local/include/vips/object.h:528: error: ‘GParamSpec’ has not been declared
/usr/local/include/vips/object.h:529: error: ‘guint’ has not been declared
/usr/local/include/vips/object.h:532: error: ‘gboolean’ does not name a type
/usr/local/include/vips/object.h:539: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/object.h:540: error: expected primary-expression before ‘set’
/usr/local/include/vips/object.h:540: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:540: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:540: error: initializer expression list treated as compound expression
/usr/local/include/vips/object.h:548: error: typedef ‘VipsTypeMapFn’ is initialized (use __typeof__ instead)
/usr/local/include/vips/object.h:548: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/object.h:548: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:549: error: typedef ‘VipsTypeMap2Fn’ is initialized (use __typeof__ instead)
/usr/local/include/vips/object.h:549: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/object.h:549: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:549: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:551: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/object.h:551: error: ‘VipsTypeMap2Fn’ was not declared in this scope
/usr/local/include/vips/object.h:551: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:551: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:551: error: initializer expression list treated as compound expression
/usr/local/include/vips/object.h:552: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/object.h:552: error: ‘VipsTypeMapFn’ was not declared in this scope
/usr/local/include/vips/object.h:552: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:552: error: initializer expression list treated as compound expression
/usr/local/include/vips/object.h:553: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/object.h:554: error: ‘GType’ does not name a type
/usr/local/include/vips/object.h:556: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/object.h:556: error: expected primary-expression before ‘fn’
/usr/local/include/vips/object.h:556: error: expected primary-expression before ‘void’
/usr/local/include/vips/object.h:556: error: initializer expression list treated as compound expression
/usr/local/include/vips/object.h:561: error: ‘GObject’ has not been declared
/usr/local/include/vips/object.h:566: error: ‘gboolean’ has not been declared
In file included from /usr/local/include/vips/vips.h:102,
                 from ../src/transform.cc:39:
/usr/local/include/vips/type.h:52: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:83: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:93: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/type.h:93: error: expected primary-expression before ‘sizeof_type’
/usr/local/include/vips/type.h:93: error: expected primary-expression before ‘int’
/usr/local/include/vips/type.h:93: error: initializer expression list treated as compound expression
/usr/local/include/vips/type.h:97: error: ‘GType’ has not been declared
/usr/local/include/vips/type.h:105: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:113: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:121: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:129: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:140: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:148: error: ‘GType’ does not name a type
/usr/local/include/vips/type.h:150: error: variable or field ‘vips_value_set_area’ declared void
/usr/local/include/vips/type.h:150: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:150: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:150: error: expected primary-expression before ‘free_fn’
/usr/local/include/vips/type.h:150: error: expected primary-expression before ‘void’
/usr/local/include/vips/type.h:151: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/local/include/vips/type.h:153: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/local/include/vips/type.h:154: error: variable or field ‘vips_value_set_save_string’ declared void
/usr/local/include/vips/type.h:154: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:154: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:154: error: expected primary-expression before ‘const’
/usr/local/include/vips/type.h:155: error: variable or field ‘vips_value_set_save_stringf’ declared void
/usr/local/include/vips/type.h:155: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:155: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:155: error: expected primary-expression before ‘const’
/usr/local/include/vips/type.h:155: error: expected primary-expression before ‘...’ token
/usr/local/include/vips/type.h:158: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/local/include/vips/type.h:159: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:159: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:159: error: expected primary-expression before ‘const’
/usr/local/include/vips/type.h:159: error: initializer expression list treated as compound expression
/usr/local/include/vips/type.h:161: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/local/include/vips/type.h:162: error: variable or field ‘vips_value_set_blob’ declared void
/usr/local/include/vips/type.h:162: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:162: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:163: error: expected primary-expression before ‘free_fn’
/usr/local/include/vips/type.h:163: error: expected primary-expression before ‘void’
/usr/local/include/vips/type.h:163: error: expected primary-expression before ‘length’
/usr/local/include/vips/type.h:165: error: variable or field ‘vips_value_set_array’ declared void
/usr/local/include/vips/type.h:165: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:165: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:166: error: expected primary-expression before ‘int’
/usr/local/include/vips/type.h:166: error: ‘GType’ was not declared in this scope
/usr/local/include/vips/type.h:166: error: expected primary-expression before ‘sizeof_type’
/usr/local/include/vips/type.h:167: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/local/include/vips/type.h:170: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/local/include/vips/type.h:171: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:171: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:171: error: expected primary-expression before ‘const’
/usr/local/include/vips/type.h:171: error: expected primary-expression before ‘int’
/usr/local/include/vips/type.h:171: error: initializer expression list treated as compound expression
/usr/local/include/vips/type.h:173: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/local/include/vips/type.h:174: error: ‘GValue’ was not declared in this scope
/usr/local/include/vips/type.h:174: error: ‘value’ was not declared in this scope
/usr/local/include/vips/type.h:174: error: expected primary-expression before ‘int’
/usr/local/include/vips/type.h:174: error: initializer expression list treated as compound expression
In file included from /usr/local/include/vips/vips.h:105,
                 from ../src/transform.cc:39:
/usr/local/include/vips/rect.h:50: error: ‘gboolean’ does not name a type
/usr/local/include/vips/rect.h:51: error: ‘gboolean’ does not name a type
/usr/local/include/vips/rect.h:52: error: ‘gboolean’ does not name a type
/usr/local/include/vips/rect.h:53: error: ‘gboolean’ does not name a type
In file included from /usr/local/include/vips/vips.h:107,
                 from ../src/transform.cc:39:
/usr/local/include/vips/private.h:82: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/private.h:83: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/private.h:92: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/private.h:93: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/private.h:105: error: ‘gboolean’ does not name a type
/usr/local/include/vips/private.h:164: error: redefinition of ‘VipsArgument* vips__argument_table_lookup’
/usr/local/include/vips/object.h:293: error: ‘VipsArgument* vips__argument_table_lookup’ previously defined here
/usr/local/include/vips/private.h:164: error: ‘VipsArgumentTable’ was not declared in this scope
/usr/local/include/vips/private.h:164: error: ‘table’ was not declared in this scope
/usr/local/include/vips/private.h:165: error: ‘GParamSpec’ was not declared in this scope
/usr/local/include/vips/private.h:165: error: ‘pspec’ was not declared in this scope
In file included from /usr/local/include/vips/vips.h:110,
                 from ../src/transform.cc:39:
/usr/local/include/vips/image.h:229: error: ‘gint64’ does not name a type
/usr/local/include/vips/image.h:230: error: ‘gint64’ does not name a type
/usr/local/include/vips/image.h:232: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:309: error: ‘guint32’ does not name a type
/usr/local/include/vips/image.h:319: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:320: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:325: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:326: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:335: error: ‘guint64’ does not name a type
/usr/local/include/vips/image.h:341: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:351: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:352: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:358: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/image.h:371: error: ‘gint64’ does not name a type
/usr/local/include/vips/image.h:379: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:388: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:424: error: ‘GType’ does not name a type
/usr/local/include/vips/image.h:429: error: ‘guint64’ does not name a type
/usr/local/include/vips/image.h:481: error: ‘gboolean’ has not been declared
/usr/local/include/vips/image.h:483: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:484: error: ‘gboolean’ has not been declared
/usr/local/include/vips/image.h:491: error: ‘guint64’ has not been declared
/usr/local/include/vips/image.h:496: error: ‘gboolean’ has not been declared
/usr/local/include/vips/image.h:501: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:502: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:503: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:512: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:513: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:514: error: ‘gboolean’ does not name a type
/usr/local/include/vips/image.h:515: error: ‘gboolean’ does not name a type
In file included from /usr/local/include/vips/vips.h:112,
                 from ../src/transform.cc:39:
/usr/local/include/vips/error.h:47: error: variable or field ‘vips_error_g’ declared void
/usr/local/include/vips/error.h:47: error: ‘GError’ was not declared in this scope
/usr/local/include/vips/error.h:47: error: ‘error’ was not declared in this scope
In file included from /usr/local/include/vips/vips.h:113,
                 from ../src/transform.cc:39:
/usr/local/include/vips/format.h:76: error: expected identifier before ‘*’ token
/usr/local/include/vips/format.h:76: error: ‘gboolean’ declared as function returning a function
/usr/local/include/vips/format.h:106: error: ‘GType’ does not name a type
/usr/local/include/vips/format.h:127: error: ‘gboolean’ has not been declared
In file included from /usr/local/include/vips/vips.h:114,
                 from ../src/transform.cc:39:
/usr/local/include/vips/region.h:79: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/region.h:92: error: ‘gboolean’ does not name a type
/usr/local/include/vips/region.h:100: error: ‘GType’ does not name a type
In file included from /usr/local/include/vips/vips.h:115,
                 from ../src/transform.cc:39:
/usr/local/include/vips/generate.h:44: error: ‘gboolean’ has not been declared
In file included from /usr/local/include/vips/vips.h:116,
                 from ../src/transform.cc:39:
/usr/local/include/vips/interpolate.h:89: error: ‘GType’ does not name a type
In file included from /usr/local/include/vips/semaphore.h:44,
                 from /usr/local/include/vips/vips.h:117,
                 from ../src/transform.cc:39:
/usr/local/include/vips/thread.h:59: error: variable or field ‘vips__g_thread_init’ declared void
/usr/local/include/vips/thread.h:59: error: ‘GThreadFunctions’ was not declared in this scope
/usr/local/include/vips/thread.h:59: error: ‘vtable’ was not declared in this scope
/usr/local/include/vips/thread.h:60: error: ‘gpointer’ does not name a type
/usr/local/include/vips/thread.h:61: error: ‘gpointer’ does not name a type
/usr/local/include/vips/thread.h:62: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/local/include/vips/thread.h:75: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/local/include/vips/thread.h:76: error: variable or field ‘vips__g_mutex_free’ declared void
/usr/local/include/vips/thread.h:76: error: ‘GMutex’ was not declared in this scope
/usr/local/include/vips/thread.h:76: error: expected primary-expression before ‘)’ token
/usr/local/include/vips/thread.h:77: error: variable or field ‘vips__g_mutex_lock’ declared void
/usr/local/include/vips/thread.h:77: error: ‘GMutex’ was not declared in this scope
/usr/local/include/vips/thread.h:77: error: expected primary-expression before ‘)’ token
/usr/local/include/vips/thread.h:78: error: variable or field ‘vips__g_mutex_unlock’ declared void
/usr/local/include/vips/thread.h:78: error: ‘GMutex’ was not declared in this scope
/usr/local/include/vips/thread.h:78: error: expected primary-expression before ‘)’ token
In file included from /usr/local/include/vips/vips.h:117,
                 from ../src/transform.cc:39:
/usr/local/include/vips/semaphore.h:52: error: expected ‘;’ before ‘*’ token
/usr/local/include/vips/semaphore.h:53: error: expected ‘;’ before ‘*’ token
In file included from /usr/local/include/vips/vips.h:118,
                 from ../src/transform.cc:39:
/usr/local/include/vips/threadpool.h:84: error: ‘gboolean’ does not name a type
/usr/local/include/vips/threadpool.h:99: error: ‘GType’ does not name a type
/usr/local/include/vips/threadpool.h:112: error: ‘gboolean’ has not been declared
In file included from /usr/local/include/vips/vips.h:119,
                 from ../src/transform.cc:39:
/usr/local/include/vips/header.h:88: error: ‘guint64’ does not name a type
/usr/local/include/vips/header.h:115: error: ‘GValue’ has not been declared
/usr/local/include/vips/header.h:116: error: ‘GValue’ has not been declared
/usr/local/include/vips/header.h:118: error: ‘GType’ does not name a type
/usr/local/include/vips/header.h:119: error: ‘gboolean’ does not name a type
/usr/local/include/vips/header.h:121: error: ‘GValue’ has not been declared
In file included from /usr/local/include/vips/vips.h:120,
                 from ../src/transform.cc:39:
/usr/local/include/vips/operation.h:54: error: typedef ‘gboolean’ is initialized (use __typeof__ instead)
/usr/local/include/vips/operation.h:54: error: ‘VipsOperationBuildFn’ was not declared in this scope
/usr/local/include/vips/operation.h:66: error: ‘guint’ does not name a type
/usr/local/include/vips/operation.h:67: error: ‘gboolean’ does not name a type
/usr/local/include/vips/operation.h:79: error: ‘GType’ does not name a type
/usr/local/include/vips/operation.h:88: error: variable or field ‘vips_call_options’ declared void
/usr/local/include/vips/operation.h:88: error: ‘GOptionGroup’ was not declared in this scope
/usr/local/include/vips/operation.h:88: error: ‘group’ was not declared in this scope
/usr/local/include/vips/operation.h:88: error: expected primary-expression before ‘*’ token
/usr/local/include/vips/operation.h:88: error: ‘operation’ was not declared in this scope
/usr/local/include/vips/operation.h:101: error: variable or field ‘vips_cache_set_dump’ declared void
/usr/local/include/vips/operation.h:101: error: ‘gboolean’ was not declared in this scope
/usr/local/include/vips/operation.h:102: error: variable or field ‘vips_cache_set_trace’ declared void
/usr/local/include/vips/operation.h:102: error: ‘gboolean’ was not declared in this scope
In file included from /usr/local/include/vips/vips.h:121,
                 from ../src/transform.cc:39:
/usr/local/include/vips/foreign.h:79: error: ‘GType’ does not name a type
/usr/local/include/vips/foreign.h:118: error: ‘gboolean’ does not name a type
/usr/local/include/vips/foreign.h:123: error: ‘gboolean’ does not name a type
/usr/local/include/vips/foreign.h:151: error: expected identifier before ‘*’ token
/usr/local/include/vips/foreign.h:151: error: ‘gboolean’ declared as function returning a function
/usr/local/include/vips/foreign.h:196: error: ‘GType’ does not name a type
/usr/local/include/vips/foreign.h:202: error: ‘gboolean’ does not name a type
/usr/local/include/vips/foreign.h:282: error: ‘gboolean’ does not name a type
/usr/local/include/vips/foreign.h:285: error: ‘GType’ does not name a type
In file included from /usr/local/include/vips/vips.h:123,
                 from ../src/transform.cc:39:
/usr/local/include/vips/enumtypes.h:7: error: ‘G_BEGIN_DECLS’ does not name a type
/usr/local/include/vips/enumtypes.h:12: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:14: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:16: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:18: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:21: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:23: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:25: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:27: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:29: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:31: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:33: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:36: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:38: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:40: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:42: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:44: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:47: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:50: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:52: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:54: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:56: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:58: error: ‘GType’ does not name a type
/usr/local/include/vips/enumtypes.h:61: error: ‘GType’ does not name a type
In file included from /usr/local/include/vips/vips.h:125,
                 from ../src/transform.cc:39:
/usr/local/include/vips/arithmetic.h:37: error: expected constructor, destructor, or type conversion before ‘extern’
In file included from /usr/include/c++/4.2.1/bits/locale_facets.tcc:42,
                 from /usr/include/c++/4.2.1/locale:46,
                 from /usr/include/c++/4.2.1/bits/istream.tcc:46,
                 from /usr/include/c++/4.2.1/istream:845,
                 from /usr/include/c++/4.2.1/sstream:44,
                 from /usr/local/Cellar/exiv2/0.21.1/include/exiv2/types.hpp:50,
                 from /usr/local/Cellar/exiv2/0.21.1/include/exiv2/basicio.hpp:34,
                 from /usr/local/Cellar/exiv2/0.21.1/include/exiv2/exiv2.hpp:34,
                 from ../src/transform.cc:40:
/usr/include/c++/4.2.1/typeinfo:41: error: expected `}' before end of line
/usr/include/c++/4.2.1/typeinfo:41: error: expected declaration before end of line
Waf: Leaving directory `/Users/tobias/Documents/test/node/node_modules/node-vips/build'
Build failed:  -> task failed (err #1): 
    {task: cxx transform.cc -> transform_1.o}`

glib is installed:

$ brew install glib
Error: glib-2.32.3 already installed

also

$ vips -v
vips-7.28.0-Sun Jun 17 02:07:42 PDT 2012

**Comment by wwlinx** [comment]
Hi Tobias,
looks like it can't find your glib installation. you do have the glib header files and glib.h installed somewhere? you may need to change wscript in order to point it to the right place.

**Comment by tobsn** [comment]
hmm... good question... osx is confusing me :/

**Comment by eden** [comment]
Try the latest revision, `wscript` has been updated to check for the right glib.  Also, you'll need to make sure to build vips 0.26 or _older_.  Newer vips don't work currently with node-vips.  You can amend your homebrew recipe for vips by running `homebrew edit vips` and changing the lines seen in this diff https://gist.github.com/3729512.
