### ISSUE TITLE
Sharpen by default

### ISSUE THREAD

**Issue by lovell** [dosx/node-vips#10]
I notice the source of https://github.com/dosx/node-vips/blob/master/src/transform.cc#L167 includes "TODO(walt): add sharpening?".

The vipsthumbnail tool, upon which this code is based, now performs a "mild" sharpen by default.

https://github.com/jcupitt/libvips/commit/7eb3513d462e3ebb037520468ecd4bd7c1d186da

I've backported this code to node-vips ResizeAndCrop method.

_Question for @dosx: Are you happy to accept a Pull Request making this the default behaviour to match the upstream behaviour?_

Pros: In user testing the images it produces are significantly clearer.

Cons: In some basic performance testing I found the sharpening step adds around 20% to the overall image processing time (although it's still very, very fast). YMMV.

**Comment by wwlinx** [comment]
Sure. I would consider adding a flag and defaulting to off at first though.

**Comment by lovell** [comment]
Thanks @wwlinx

At the moment all args are required and I'm a little worried about breaking backwards compatibility with new, optional parameters.

Here's an example of how I could add optional args using an object of key/value pairs, itself optional.

https://github.com/lovell/node-vips/commit/1fc848864405eed5d0afc3cd8554e1000e5e462e

Are you OK with this approach?

Aside: There is another optional parameter I'd like to add to ensure the output is _exactly_ the dimensions requested for non-cropped images (with strips of background colour padding at left+right or top+bottom using im_embed). This could follow the same pattern I've outlined here.
