### ISSUE TITLE
Module doesn't load

### ISSUE THREAD

**Issue by epoberezkin** [dosx/node-vips#9]
After require('vips') the error message is shown:

module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: libexiv2.so.12: cannot open shared object file: No such file or directory

It seems it has nothing to do with ImageMagick. Is it some exiv2 installation problem?

**Comment by eden** [comment]
Yes, very likely the issue is that your exiv2 installation isn't fully setup. Try running `ldconfig`. If that doesn't work check your library loading paths.

**Comment by epoberezkin** [comment]
Great! It works and passes your simple_test (with ImageMagick code commented out though, with ImageMagic it returns some error. But I'm not going to use ImageMagic anyway). Thank you very much for your help, all my issues were my own problems, obviously ;)
